#!/usr/bin/env bash
set -e

# shellcheck disable=SC1091
source "$(brew --prefix asdf)/libexec/asdf.sh"

asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs
asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp
asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby
