cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'caskroom/fonts'

brew 'ack'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'git'
brew 'git-flow'
brew 'm-cli'
brew 'n'
brew 'reattach-to-user-namespace'
brew 'readline'
# brew 'pyenv'
# brew 'pyenv-ccache'
# brew 'pyenv-virtualenvwrapper'
# brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'tmux'
brew 'wget'
brew 'yarn'

cask 'atom'
cask 'caffeine'
cask 'docker'
cask 'dropbox'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-lato'
cask 'font-monoid'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'sequel-pro'
# cask 'slack'
cask 'tower'
cask 'vagrant'
cask 'virtualbox'

# mas '1Password', id: 443987910
# mas 'Affinity Photo', id: 824183456
