#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: sphp [phpversion]"
	exit 1
fi

currentversion="`php -r \"error_reporting(0); echo str_replace('.', '', substr(phpversion(), 0, 3));\"`"
newversion="$1"

shortOld="`php -r \"error_reporting(0); echo substr(phpversion(), 0, 1);\"`"
shortNew="`php -r \"error_reporting(0); echo substr('$1', 0, 1);\"`"

brew list php$newversion 2> /dev/null > /dev/null

if [ $? -eq 0 ]; then
	echo "PHP version $newversion found"

	echo "Unlinking old binaries..."
	brew unlink php$currentversion 2> /dev/null > /dev/null

	echo "Linking new binaries..."
	brew link php$newversion

	echo "Done."
else
	echo "PHP version $newversion was not found."
	exit 1
fi
