"Bundles
	set nocompatible
	filetype off
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	Plugin 'gmarik/Vundle.vim'
	Plugin 'tomasr/molokai'
	"Add more plugins here
	call vundle#end()
	filetype plugin indent on
