#!/usr/bin/env bash

# Vim plugins
if [ -d ~/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u ~/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q

# Remove broken symlinks
find -L ~/.zsh -type l -ls -exec rm {} +
find -L ~ -type l -maxdepth 1 -ls -exec rm {} +

# MacOS specific items
[ "$(uname -s)" != "Darwin" ] && exit

# Install Homebrew packages
brew update && brew bundle --global

# zsh plugins via antibody (https://getantibody.github.io/)
antibody update
antibody bundle < "$HOME/.zsh/plugins.txt" > "$HOME/.zsh/plugins.zsh"

# VS Code setup
settings_file="$HOME/Library/Application Support/Code/User/settings.json"
[ -L "$settings_file" ] || (rm -f "$settings_file" && ln -s "$HOME/.dotfiles/vscode/settings.json" "$settings_file")

installed_exts=$(code --list-extensions)
while read -r ext; do
  [[ "${installed_exts}" =~ $ext ]] || code --install-extension "$ext"
done < "$HOME/.dotfiles/vscode/extensions.txt"

# We're assuming the default profile
ffprofile=$(cd "$HOME/Library/Application Support/Firefox/Profiles" && cd $(ls | grep default) && pwd)
[ -L "$ffprofile/user.js" ] || ln -s "$HOME/.dotfiles/firefox/user.js" "$ffprofile/user.js"
