#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

# Vim plugins
if [ -d ~/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u ~/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q

# Remove broken symlinks
find -L ~/.zsh -type l -ls -exec rm {} +
find -L ~ -type l -maxdepth 1 -ls -exec rm {} +

# MacOS specific items
[ "$(uname -s)" != "Darwin" ] && exit

# Install Homebrew packages
brew update && brew bundle --global

# zsh plugins via antibody (https://getantibody.github.io/)
antibody update
antibody bundle < "$HOME/.zsh/plugins.txt" > "$HOME/.zsh/plugins.zsh"

# VS Code setup
vssettings="$HOME/Library/Application Support/Code/User/settings.json"
[ -L "$vssettings" ] || (rm -f "$vssettings" && ln -s "$DIR/vscode/settings.json" "$vssettings")

installed_exts=$(code --list-extensions)
while read -r ext; do
  [[ "${installed_exts}" =~ $ext ]] || code --install-extension "$ext"
done < "$DIR/vscode/extensions.txt"

# Firefox settings
$DIR/firefox/updater.sh -lusv -o "$DIR/firefox/user.js"
