#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if [ ! -f "$DIR/gitconfig.local" ]; then
  printf "⚠️ \033[00;33mMissing ~/.dotfiles/gitconfig.local\033[0m\n"
fi

[ -f "$HOME/.zsh/oh-my-zsh.sh" ] && rm -rf ~/.zsh
