#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname $0)"/..

# Run the Homebrew installer first because others depend on packages
sh -c "./macos/homebrew.sh"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
