#!/usr/bin/env bash
#
# Setup a fresh Mac
set -ue

info() {
  printf "🛠 \033[00;36m%s\033[0m\n" "$1"
}

success() {
  printf "🙌 \033[00;32m%s\033[0m\n" "$1"
}

warn() {
  printf "⚠️ \033[00;33m%s\033[0m\n" "$1"
}

user() {
  printf "⁉️ \033[0;33m%s\033[0m" "$1"
}

abort() {
  printf "☠️ \033[0;31m%s\033[0m\n" "$1"
  exit 1
}

[ "$(uname -s)" != "Darwin" ] && abort "This only works on MacOS"

user "Hostname: "
read -r hostname

if [ -n "$hostname" ]; then
  info "Setting hostname..."
  sudo hostname "$hostname"
  sudo scutil --set ComputerName "$hostname"
  sudo scutil --set HostName "$hostname"
  sudo scutil --set LocalHostName "$hostname"
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$hostname"
fi

if ! command -v brew >/dev/null; then
  info "Installing Homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

info "Installing some requirements via Homebrew"
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
brew "rcm"
EOF

if ! test -d "$HOME/.zsh"; then
  info "Setting up oh-my-zsh"
  git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh "$HOME/.zsh"
  git clone --depth=1 https://github.com/denysdovhan/spaceship-prompt "$HOME/.zsh/custom/themes/spaceship-prompt"
  ln -s "$HOME/.zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" "$HOME/.zsh/custom/themes/spaceship.zsh-theme"
fi

info "Installing dotfiles"
[ ! -d "$HOME/.dotfiles" ] && git clone https://github.com/mloberg/dotfiles.git ~/.dotfiles
RCRC="$HOME/.dotfiles/rcrc" rcup

info "Set default shell to zsh"
grep --quiet "$(command -v zsh)" /etc/shells || (command -v zsh | sudo tee -a /etc/shells)
chsh -s "$(command -v zsh)"

info "Configuring Vagrant to not require passwords"
if [ ! -f /etc/sudoers.d/vagrant ]; then
  cat <<EOF | sudo tee /etc/sudoers.d/vagrant
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = $(command -v sed) -E -e /*/ d -ibak /etc/exports
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = $(command -v sed) -i -e /*/ d /etc/hosts
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE, VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
EOF
fi

info "Setting MacOS defaults"
~/.macos

info "Turning Bluetooth off"
m bluetooth disable

user "Clear Dock? [y/N] "
read -r clear
if [[ "${clear}" =~ ^(y|Y)$ ]]; then
  info "Clearing the Dock"
  m dock prune
fi

info "Updating software"
sudo softwareupdate -i -a

info "Securing Mac"
~/.dotfiles/script/lockdown

success "Success"
warn "Firefox setup not complete. See ~/.dotfiles/firefox/addons.md"
warn "Rebooting in 5s"
sleep 5
m restart
