#!/usr/bin/env bash
#
# Setup a fresh Mac
set -ue

info() {
  printf "🛠 \033[00;36m%s\033[0m\n" "$1"
}

success() {
  printf "🙌 \033[00;32m%s\033[0m\n" "$1"
}

warn() {
  printf "⚠️ \033[00;33m%s\033[0m\n" "$1"
}

user() {
  printf "⁉️ \033[0;33m%s\033[0m" "$1"
}

abort() {
  printf "☠️ \033[0;31m%s\033[0m\n" "$1"
  exit 1
}

[ "$(uname -s)" != "Darwin" ] && abort "This only works on MacOS"

user "Hostname: "
read -r hostname

if [ -n "$hostname" ]; then
  info "Setting hostname..."
  sudo hostname "$hostname"
  sudo scutil --set ComputerName "$hostname"
  sudo scutil --set HostName "$hostname"
  sudo scutil --set LocalHostName "$hostname"
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$hostname"
fi

if ! command -v brew >/dev/null; then
  info "Installing Homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

info "Installing some requirements via Homebrew"
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
brew "rcm"
brew "bash"
EOF

info "Using a newer Bash"
chsh -s "$(command -v bash)"

info "Installing dotfiles"
[ ! -d "$HOME/.dotfiles" ] && git clone https://github.com/mloberg/dotfiles.git ~/.dotfiles
RCRC="$HOME/.dotfiles/rcrc" rcup

info "Configuring Vagrant to not require passwords"
if [ ! -f /etc/sudoers.d/vagrant ]; then
  cat <<EOF | sudo tee /etc/sudoers.d/vagrant
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = $(command -v sed) -E -e /*/ d -ibak /etc/exports
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = $(command -v sed) -i -e /*/ d /etc/hosts
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE, VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
EOF
fi

info "Setting up DNSCrypt"
rm -f /usr/local/etc/dnscrypt-proxy.toml
ln -s "$HOME/.dotfiles/config/dnscrypt-proxy.toml" /usr/local/etc/dnscrypt-proxy.toml
sudo brew services start dnscrypt-proxy

info "Setting up Dnsmasq"
rm -f /usr/local/etc/dnsmasq.conf
ln -s "$HOME/.dotfiles/config/dnsmasq.conf" /usr/local/etc/dnsmasq.conf
sudo brew services start dnsmasq-dnssec
sudo networksetup -setdnsservers "Wi-Fi" 127.0.0.1
networksetup -listallnetworkservices | grep Wired >/dev/null && sudo networksetup -setdnsservers "Wired" 127.0.0.1
dig +dnssec icann.org | grep "status: NOERROR" >/dev/null || warn "Error in Dnsmasq configuration!"

info "Setup Privoxy"
rm -f /usr/local/etc/privoxy/config
rm -f /usr/local/etc/privoxy/user.action
ln -s "$HOME/.dotfiles/config/privoxy/config" /usr/local/etc/privoxy/config
ln -s "$HOME/.dotfiles/config/privoxy/user.action" /usr/local/etc/privoxy/user.action
brew services start privoxy
sudo networksetup -setwebproxy "Wi-Fi" 127.0.0.1 8118
sudo networksetup -setsecurewebproxy "Wi-Fi" 127.0.0.1 8118
networksetup -listallnetworkservices | grep Wired >/dev/null && sudo networksetup -setwebproxy "Wired" 127.0.0.1 8118 && sudo networksetup -setsecurewebproxy "Wired" 127.0.0.1 8118

info "Setting MacOS defaults"
~/.macos

info "Turning Bluetooth off"
m bluetooth disable

user "Clear Dock? [y/N] "
read -r clear
if [[ "${clear}" =~ ^(y|Y)$ ]]; then
  info "Clearing the Dock"
  m dock prune
fi

info "Updating software"
sudo softwareupdate -i -a

user "Secure Mac? [y/N] "
read -r secure
if [[ "${secure}" =~ ^(y|Y)$ ]]; then
  ~/.dotfiles/script/lockdown
fi

success "Success"
warn "Rebooting"
m restart
