#!/usr/bin/env bash

install_asdf_plugin() {
    local name="$1"
    local url="$2"

    if ! asdf plugin-list | grep -Fq "$name"; then
        asdf plugin add "$name" "$url"
    else
        asdf plugin update "$name"
    fi
}

# shellcheck disable=SC1090
source $(brew --prefix asdf)/libexec/asdf.sh

install_asdf_plugin nodejs https://github.com/asdf-vm/asdf-nodejs
install_asdf_plugin terraform https://github.com/asdf-community/asdf-hashicorp
install_asdf_plugin golang https://github.com/kennyp/asdf-golang

install_asdf_plugin ruby https://github.com/asdf-vm/asdf-ruby
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))
bundle config --global path vendor/bundle
