#!/usr/bin/env bash

install_gh_extension() {
    local extension="$1"

    if ! gh extension list | grep -Fq "$extension"; then
        gh extension install "$extension"
    fi
}

gh extension upgrade --all

install_gh_extension mloberg/gh-prs
install_gh_extension mloberg/gh-view
