#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

confs=(settings.json keybindings.json)
for conf in ${confs[*]}; do
  [ -L "$HOME/Library/Application Support/Code/User/$conf" ] && continue
  ln -s "$DIR/vscode/$conf" "$HOME/Library/Application Support/Code/User/$conf"
done

# install missing plugins
diff -B <(sort < "$DIR/vscode/extensions.txt") <(code --list-extensions | sort) | \
  grep '^<' | sed -E 's/<[[:space:]]+(.*)/\1/g' | \
  xargs -n 1 code --install-extension
