#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

PROFILE="$HOME/.firefox"
[ -f "$PROFILE/prefs.js" ] || /Applications/Firefox.app/Contents/MacOS/firefox -CreateProfile "mloberg $PROFILE"

"$DIR/firefox/updater.sh" -p "$PROFILE" -usv -o "$DIR/firefox/overrides.js,$DIR/firefox/local.js"
