#!/usr/bin/env bash

src="$( cd -- "$(dirname "$0")/../.." >/dev/null 2>&1 ; pwd -P )/firefox/user.js"

for profile in ~/Library/Application\ Support/Firefox/Profiles/*; do
    dest="$profile/user.js"
    if [ ! -d "$profile" ]; then
        >&2 echo "WARN: No Firefox profile found"
    elif [ ! -L "$dest" ]; then
        ln -s "$src" "$dest"
    fi
done
