services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilisearch-data:/data.ms
    ports:
      - 7700:7700

volumes:
  redis-data:
  postgres-data:
  mysql-data:
  meilisearch-data:
